# Generated by Django 4.2.7 on 2026-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='app_rooms',
        ),
    ]
