# Generated by Django 4.2.7 on 2026-05-04 02:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'app_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, choices=[('1BHK', '1BHK'), ('2BHK', '2BHK'), ('3BHK', '3BHK'), ('Studio', 'Studio'), ('Shared', 'Shared')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SavedRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Saved Room',
                'verbose_name_plural': 'Saved Rooms',
                'db_table': 'app_saved_rooms',
                'unique_together': {('user_id', 'room')},
            },
        ),
    ]
