# Generated by Django 4.2.7 on 2026-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='app_users',
        ),
    ]
