# Generated by Django 4.2.7 on 2026-05-04

from django.db import migrations, models
import uuid


def create_app_users_if_missing(apps, schema_editor):
    existing_tables = schema_editor.connection.introspection.table_names()
    if 'app_users' in existing_tables:
        return

    vendor = schema_editor.connection.vendor
    created_at_type = 'timestamp with time zone' if vendor == 'postgresql' else 'datetime'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'''
            CREATE TABLE app_users (
                id varchar(255) PRIMARY KEY,
                name varchar(255) NOT NULL,
                email varchar(254) NOT NULL UNIQUE,
                phone varchar(20) NOT NULL,
                role varchar(20) NOT NULL,
                created_at {created_at_type} NOT NULL,
                updated_at {created_at_type} NOT NULL
            )
            '''
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RunPython(create_app_users_if_missing, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landowner', 'Landowner'), ('both', 'Owner & Tenant')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='app_theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='English', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='location_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('contacts', 'Contacts only')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'app_support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
